services:
  postgres:
    image: postgres:15
    container_name: booking_postgres
    environment:
      POSTGRES_DB: booking_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking_network

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: booking_pgbouncer
    environment:
      DATABASES_HOST: postgres
      DATABASES_PORT: 5432
      DATABASES_USER: postgres
      DATABASES_PASSWORD: postgres123
      DATABASES_DBNAME: booking_app
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      AUTH_TYPE: trust
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    depends_on:
      - postgres
    networks:
      - booking_network

volumes:
  postgres_data:

networks:
  booking_network:
    driver: bridge
